# Generated by Django 5.0.5 on 2024-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_date', models.DateField()),
                ('sells_plan', models.IntegerField()),
                ('actual_sells_plan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id_seller', models.IntegerField(primary_key=True, serialize=False)),
                ('id_storage', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SellerPlan',
            fields=[
                ('id_seller', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_date', models.DateField()),
                ('sells_plan', models.IntegerField()),
                ('actual_sells_plan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id_storage', models.IntegerField()),
                ('id_item', models.IntegerField()),
                ('id_sell', models.IntegerField(primary_key=True, serialize=False)),
                ('sell_data', models.DateField()),
                ('cnt', models.IntegerField()),
                ('id_seller', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id_storage', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoragePlan',
            fields=[
                ('id_storage', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_date', models.DateField()),
                ('sells_plan', models.IntegerField()),
                ('actual_sells_plan', models.IntegerField()),
            ],
        ),
    ]
