# Generated by Django 5.0.5 on 2024-05-09 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_remove_item_actual_sells_plan_remove_item_plan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='id_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.storage'),
        ),
        migrations.AlterField(
            model_name='sellerplan',
            name='id_seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Store.seller'),
        ),
        migrations.AlterField(
            model_name='sells',
            name='id_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.item'),
        ),
        migrations.AlterField(
            model_name='sells',
            name='id_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.seller'),
        ),
        migrations.AlterField(
            model_name='sells',
            name='id_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.storage'),
        ),
        migrations.AlterField(
            model_name='storageplan',
            name='id_storage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Store.storage'),
        ),
    ]
