# Generated by Django 5.0.5 on 2024-05-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_item_id_item_alter_seller_id_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sells',
            old_name='id_item',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='sells',
            old_name='id_seller',
            new_name='Seller',
        ),
        migrations.RenameField(
            model_name='sells',
            old_name='id_storage',
            new_name='Storage',
        ),
        migrations.AlterField(
            model_name='sells',
            name='id_sell',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
