# Generated by Django 5.0.5 on 2024-05-09 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_alter_seller_id_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='id_storage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Store.storage'),
        ),
    ]
