# Generated by Django 5.0.5 on 2024-05-12 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_alter_seller_id_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerplan',
            name='plan_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sells',
            name='sell_data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storageplan',
            name='plan_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
