# Generated by Django 5.0.5 on 2024-05-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='actual_sells_plan',
        ),
        migrations.RemoveField(
            model_name='item',
            name='plan_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sells_plan',
        ),
        migrations.AddField(
            model_name='item',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
