# Generated by Django 5.0.5 on 2024-05-09 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_sells_id_item_alter_sells_id_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='id_storage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Store.storage'),
        ),
    ]
