# Generated by Django 5.0.5 on 2024-05-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_sells_id_item_alter_sells_id_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id_item',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='id_seller',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storage',
            name='id_storage',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
