version: "3.9"

services:
  postgres_db:
    image: postgres:alpine
    container_name: postgres_docker
    ports:
      - "5432:5432"
    volumes:
      - ~/.pg/data:/var/lib/postgresql/data
    env_file:
      - .env
  lab9:
    build:
      dockerfile: Dockerfile
      context: .
    image: lab9
    container_name: lab9
    ports:
      - "80:80"
    depends_on:
      - postgres_db
    env_file:
      - .env
